// Generated by hand from the Firebase Console (Project settings > Your apps),
// since `flutterfire configure` couldn't run in this environment. Mirrors
// what that command would have generated for the Android and Web apps.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have only been configured for android and web. '
          'Register an app for this platform in the Firebase Console to add it here.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOkkg5GGe9y1HN18ruXDoKb4akscSWGKs',
    appId: '1:1039931954103:android:3f087635b318a8d36e8e32',
    messagingSenderId: '1039931954103',
    projectId: 'alu-intern-link',
    storageBucket: 'alu-intern-link.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_FC3bWERUTPLI-vKccN61maqMZ4i_-hw',
    appId: '1:1039931954103:web:7c4e0472f1f35dd16e8e32',
    messagingSenderId: '1039931954103',
    projectId: 'alu-intern-link',
    authDomain: 'alu-intern-link.firebaseapp.com',
    storageBucket: 'alu-intern-link.firebasestorage.app',
    measurementId: 'G-0W20ET9D0W',
  );
}
